# Generated by Django 2.2.10 on 2021-08-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlist',
            name='age',
            field=models.IntegerField(),
        ),
    ]
